name: "coverage"
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Install deps
      - run: yarn install

      - name: run tests
      - run: yarn coverage
